from random import randint

class Client:

    account = {}

    def __init__(self, name, address, account, deposit):
        """Instantiates a new account with five parameters: random generated account number, 
        name, address, account, and initial deposit.
        
        Parameters
        ----------
        self : is an autogenerated random account_number to instantiate a new account number as a num
        name : takes in the full name of the account holder as a str
        address : takes in the full address of the account holder as a str
        account : takes in the account type: (checking or savings) as a str
        deposit : takes in a num as a float
        
        Returns
        ----------
        Stores account details 
        """
        
        self.account['account_number'] = randint(10000, 99999)
        self.account['name'] = name
        self.account['address'] = address
        self.account['account type'] = account
        self.account['balance'] = deposit

    def withdraw(self, amount):
        """Decreases balance number by some applied amount.
        
        Parameters
        ----------
        amount : new amount to be subtracted from balance
        
        Returns
        ----------
        balance -= amount
        """
        if self.account['balance'] >= amount:
            self.account['balance'] -= amount
            print()
            print("The sum of {} has been withdrawn from your account balance.".format(amount))
            self.balance()
        else:
            print()
            print("Insufficient funds!")
            self.balance()

    def deposit(self, amount):
        """Increases balance number by some applied amount.
        
        Parameters
        ----------
        amount : new amount to be added to balance
        
        Returns
        ----------
        balance += amount
        """        

        self.account['balance'] += amount
        print()
        print("The sum of {} has been added to your account balance.".format(amount))
        self.balance()

    def balance(self):
        """This function presents the balance.
        
        Parameters
        ----------
        self.account : the accont number
        
        Returns
        ----------
        The current balance from the stated account
        """
        print()
        print("Your current account balance is: {} ".format(self.account['balance']))