class Bank:

    name = 'Springboard Federal Credit Union'
    clients = []

    def update_db(self, client):
        """This function updates the internal memory database with clients account information.
        
        Parameters
        ----------
        self : is the autogenerated index in the database to house account details.
        client : is the client details from the client file
        
        Returns
        ----------
        Stores account details and returns the account information for indexing later.
        """
        self.clients.append(client)

    def authentication(self, name, account_number):
        """This function validates users credentials to allow retrieval of information later.
        
        Parameters
        ----------
        name : takes in the full name of the account holder as a str.
        account_number : is the autogenerated random account_number from client.py file
        
        Returns
        ----------
        Stores account details and returns the account information for indexing later.
        """
        for i in range(len(self.clients)):
            if name in self.clients[i].account.values() and account_number in self.clients[i].account.values():
                print()
                print("Authentication successful!")
                print("==========================================")
                return self.clients[i]